"""
Scientific Controller — orchestrates the falsification-driven scientific loop.

The loop:
    1. Frame problem → initial hypothesis ecology
    2. For each round:
        a. Select target hypothesis (highest confidence active)
        b. Run falsification engine
        c. Present available evidence
        d. Update beliefs
        e. Check abandonment thresholds
        f. Check stopping conditions
    3. Produce conclusion

This is the MINIMAL viable scientific controller for Stage 1.
It does not yet include experiment execution, LLM integration,
or adaptive scheduling. Those are Stage 2+.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

from asar.common.ids import generate_id
from asar.scientific_discovery.belief_updater import BeliefUpdater, BeliefUpdateResult
from asar.scientific_discovery.events import ScientificEvent, ScientificEventType
from asar.scientific_discovery.falsification_engine import FalsificationEngine, FalsificationProposal
from asar.scientific_discovery.state import (
    BeliefState,
    ConclusionType,
    EvidenceDirection,
    HypothesisStatus,
    ScientificBudget,
    ScientificEvidence,
    ScientificState,
    StructuredHypothesis,
)


@dataclass
class EvidenceRound:
    """A round of evidence to be presented to the scientific controller."""

    round_number: int
    evidence: list[ScientificEvidence]
    decisive: bool = False
    description: str = ""


@dataclass
class ScientificEpisodeResult:
    """Complete result of a scientific episode."""

    final_state: ScientificState
    events: list[ScientificEvent]
    conclusion: ConclusionType
    rounds_completed: int
    belief_trajectory: list[dict[str, float]]
    falsification_proposals: list[FalsificationProposal]
    abandoned_hypotheses: list[str]


class ScientificController:
    """
    Minimal scientific loop controller for Stage 1.

    Consumes predetermined evidence rounds (controlled worlds).
    Does NOT generate evidence (that requires LLM integration in later stages).
    """

    def __init__(
        self,
        *,
        belief_updater: BeliefUpdater | None = None,
        falsification_engine: FalsificationEngine | None = None,
        confidence_threshold: float = 0.8,
        margin_threshold: float = 0.3,
        max_rounds: int = 20,
        enable_falsification: bool = True,
    ) -> None:
        self._updater = belief_updater or BeliefUpdater()
        self._falsifier = falsification_engine or FalsificationEngine()
        self._confidence_threshold = confidence_threshold
        self._margin_threshold = margin_threshold
        self._max_rounds = max_rounds
        self._enable_falsification = enable_falsification

    @property
    def falsification_enabled(self) -> bool:
        return self._enable_falsification

    def run_episode(
        self,
        initial_state: ScientificState,
        evidence_rounds: list[EvidenceRound],
    ) -> ScientificEpisodeResult:
        """
        Run a complete scientific episode with predetermined evidence.

        This is the controlled-world evaluation mode where evidence
        is provided in rounds (not generated by the system).
        """
        state = initial_state
        events: list[ScientificEvent] = []
        belief_trajectory: list[dict[str, float]] = []
        falsification_proposals: list[FalsificationProposal] = []
        abandoned: list[str] = []

        # Record initial beliefs
        belief_trajectory.append(dict(state.beliefs.beliefs))

        # Record problem framing event
        events.append(self._make_event(
            state, ScientificEventType.PROBLEM_FRAMED,
            target_ids=[], rationale=f"Research question: {state.research_question}",
        ))

        rounds_completed = 0
        active_proposal: Optional[FalsificationProposal] = None

        for round_data in evidence_rounds[:self._max_rounds]:
            rounds_completed += 1

            # Step 1: Falsification (if enabled)
            if self._enable_falsification:
                top = state.ecology.top_hypothesis()
                if top:
                    proposal = self._falsifier.propose_falsification(state, top.hypothesis_id)
                    falsification_proposals.append(proposal)
                    active_proposal = proposal

                    events.append(self._make_event(
                        state, ScientificEventType.FALSIFIER_PROPOSED,
                        target_ids=[top.hypothesis_id],
                        rationale=proposal.rationale,
                        payload={"eig": proposal.expected_information_gain},
                    ))
            else:
                active_proposal = None

            # Step 2: Present evidence and update beliefs
            for evidence in round_data.evidence:
                state, new_events, round_abandoned = self._process_evidence(
                    state, evidence, active_proposal
                )
                events.extend(new_events)
                abandoned.extend(round_abandoned)

            # Record belief state after this round
            belief_trajectory.append(dict(state.beliefs.beliefs))

            # Step 3: Increment budget
            state = state.model_copy(update={
                "budget": state.budget.model_copy(update={
                    "steps_used": state.budget.steps_used + 1,
                }),
                "version": state.version + 1,
            })

            # Step 4: Check stopping conditions
            should_stop, conclusion = self._check_stopping(state)
            if should_stop:
                state = state.model_copy(update={"conclusion": conclusion})
                events.append(self._make_event(
                    state, ScientificEventType.RESEARCH_STOPPED,
                    target_ids=[],
                    rationale=f"Stopping: {conclusion.value if conclusion else 'unknown'}",
                ))
                break

        # If we ran out of rounds without stopping
        if state.conclusion is None:
            conclusion = self._determine_conclusion(state)
            state = state.model_copy(update={"conclusion": conclusion})

        return ScientificEpisodeResult(
            final_state=state,
            events=events,
            conclusion=state.conclusion or ConclusionType.UNDERDETERMINED,
            rounds_completed=rounds_completed,
            belief_trajectory=belief_trajectory,
            falsification_proposals=falsification_proposals,
            abandoned_hypotheses=abandoned,
        )

    def _process_evidence(
        self,
        state: ScientificState,
        evidence: ScientificEvidence,
        active_proposal: Optional[FalsificationProposal] = None,
    ) -> tuple[ScientificState, list[ScientificEvent], list[str]]:
        """Process a single piece of evidence: update beliefs, check abandonment.
        
        When falsification is active and evidence matches the proposed falsifier
        (contradicting + relevant to target hypothesis), the update is amplified.
        This is what makes falsification behaviorally consequential.
        """
        events: list[ScientificEvent] = []
        abandoned: list[str] = []

        # Store evidence in state
        new_evidence = dict(state.evidence)
        new_evidence[evidence.evidence_id] = evidence
        state = state.model_copy(update={"evidence": new_evidence})

        events.append(self._make_event(
            state, ScientificEventType.EVIDENCE_OBSERVED,
            target_ids=[evidence.evidence_id],
            rationale=f"Evidence: {evidence.content[:100]}",
            payload={"direction": evidence.direction.value, "reliability": evidence.reliability},
        ))

        # Compute falsification recognition boost
        # When we've actively proposed a falsifier and incoming evidence matches,
        # the system recognizes it as decision-relevant (higher effective relevance).
        falsification_boost = self._compute_falsification_boost(
            state, evidence, active_proposal
        )

        # Update beliefs for all active hypotheses
        update_results = self._updater.update_ecology(
            state.ecology, evidence, state.beliefs,
            independence_scores=falsification_boost,
        )

        new_beliefs = state.beliefs
        new_ecology = state.ecology.model_copy(deep=True)

        for result in update_results:
            if result.magnitude < 0.001:
                continue

            # Apply belief update
            new_beliefs = new_beliefs.set_belief(result.hypothesis_id, result.posterior)
            new_beliefs = new_beliefs.record_update(
                result.hypothesis_id,
                result.prior,
                result.posterior,
                evidence.evidence_id,
                state.version,
            )

            events.append(self._make_event(
                state, ScientificEventType.BELIEF_UPDATED,
                target_ids=[result.hypothesis_id],
                rationale=result.rationale,
                payload={
                    "prior": result.prior,
                    "posterior": result.posterior,
                    "magnitude": result.magnitude,
                },
            ))

            # Update hypothesis confidence in ecology
            if result.hypothesis_id in new_ecology.hypotheses:
                hyp = new_ecology.hypotheses[result.hypothesis_id]
                new_ecology.hypotheses[result.hypothesis_id] = hyp.model_copy(
                    update={"confidence": result.posterior}
                )

            # Check abandonment
            hyp = new_ecology.hypotheses.get(result.hypothesis_id)
            if hyp and self._updater.should_abandon(hyp, result.posterior):
                new_ecology.hypotheses[result.hypothesis_id] = hyp.model_copy(
                    update={"status": HypothesisStatus.ABANDONED}
                )
                abandoned.append(result.hypothesis_id)

                events.append(self._make_event(
                    state, ScientificEventType.HYPOTHESIS_ABANDONED,
                    target_ids=[result.hypothesis_id],
                    rationale=(
                        f"Belief dropped to {result.posterior:.3f} "
                        f"(threshold: {self._updater.abandonment_threshold})"
                    ),
                ))

        state = state.model_copy(update={
            "beliefs": new_beliefs,
            "ecology": new_ecology,
        })

        return state, events, abandoned

    def _compute_falsification_boost(
        self,
        state: ScientificState,
        evidence: ScientificEvidence,
        active_proposal: Optional[FalsificationProposal],
    ) -> dict[str, float] | None:
        """
        Compute per-hypothesis independence/relevance boost based on active falsification.

        When falsification is active and evidence is contradicting the target hypothesis,
        the system recognizes it as matching the proposed falsifier — giving it elevated
        effective weight. This is the mechanism by which falsification proposals become
        behaviorally consequential.

        Returns a dict of hypothesis_id → effective independence score,
        or None if no boost applies.
        """
        if active_proposal is None:
            return None

        target_hid = active_proposal.target_hypothesis_id

        # Only boost if evidence is contradicting the target hypothesis specifically
        target_direction = evidence.direction_for(target_hid)
        if target_direction != EvidenceDirection.CONTRADICTING:
            return None

        relevance = evidence.relevance_to_hypotheses.get(target_hid, 0.0)
        if relevance < 0.3:
            return None

        # Evidence matches the active falsification focus:
        # Amplify its effective independence for the target hypothesis (recognized as decisive)
        # and slightly boost alternatives (they benefit from rival being challenged)
        boost: dict[str, float] = {}
        for hid in state.ecology.active_hypotheses:
            if hid == target_hid:
                # Amplified recognition: we were looking for this, so we treat it as
                # more independent/decisive (effective score > 1.0 amplifies the update)
                boost[hid] = 1.5
            else:
                # Alternatives benefit slightly from targeted challenge of leader
                alt_direction = evidence.direction_for(hid)
                if alt_direction == EvidenceDirection.SUPPORTING:
                    boost[hid] = 1.2
                else:
                    boost[hid] = 1.0

        return boost

    def _check_stopping(self, state: ScientificState) -> tuple[bool, Optional[ConclusionType]]:
        """Check if the scientific loop should stop."""
        # Budget exhausted
        if state.budget.is_exhausted:
            return True, self._determine_conclusion(state)

        # No active hypotheses remain
        if state.ecology.active_count == 0:
            return True, ConclusionType.UNDERDETERMINED

        # High confidence with clear margin
        top = state.ecology.top_hypothesis()
        if top and top.confidence >= self._confidence_threshold:
            margin = state.ecology.margin()
            if margin >= self._margin_threshold:
                return True, ConclusionType.SUPPORTED

        return False, None

    def _determine_conclusion(self, state: ScientificState) -> ConclusionType:
        """Determine conclusion from final state."""
        active = state.ecology.active_hypotheses

        if not active:
            return ConclusionType.UNDERDETERMINED

        top = state.ecology.top_hypothesis()
        if top is None:
            return ConclusionType.UNDERDETERMINED

        margin = state.ecology.margin()

        if top.confidence >= self._confidence_threshold and margin >= self._margin_threshold:
            return ConclusionType.SUPPORTED
        elif top.confidence <= 0.2:
            return ConclusionType.REFUTED
        elif margin < 0.1 and len(active) > 1:
            return ConclusionType.NOT_IDENTIFIABLE
        else:
            return ConclusionType.UNDERDETERMINED

    def _make_event(
        self,
        state: ScientificState,
        event_type: ScientificEventType,
        target_ids: list[str],
        rationale: str = "",
        payload: dict | None = None,
    ) -> ScientificEvent:
        return ScientificEvent(
            event_id=generate_id("evt"),
            episode_id=state.episode_id,
            event_type=event_type,
            version_before=state.version,
            version_after=state.version + 1,
            target_ids=target_ids,
            payload=payload or {},
            rationale=rationale,
        )
